#!/usr/bin/bash
clear

figlet -f standard "APOLLO"
echo "-(BETA)----------------------Core-------"


#greeting section
echo "1. Who are you? "
 echo "2. can you tell me the date today?"
  echo "3. Can i see the logs of APOLLO?"
   echo "4. APOLLO what is seegson's password?"
    echo "5. I want to quit the small talk."
     echo "6. Can you lie?"
      echo "7. Why are you called APOLLO?"
     echo "8. How many lines of code are you?"
    echo "9. What is best BIF or FCK?"
   echo "10. Switch to Advanced AI CORE"
  echo "11.-Modules-"
echo "12. Locate File"
 echo "13. Reboot/Shutdown"
  echo "14. USB Options"
echo "-------------------------------------------"
echo "-------Type a Number and press Enter-------"
echo "-------------------------------------------"


read yqgz

if [[ $yqgz == 1 ]];
then clear && echo "I am the Head AI CORE computer APOLLO." && sleep 5s && bash ai


elif [[ $yqgz == 2 ]];
then clear && echo "Yes of course." && date && sleep 5s && bash ai


elif [[ $yqgz == 3 ]];
then clear && echo "Yes but i cant redirect you because i dont have perms to do that... the path is /home/seegson_admin/APOLLO/logs." && sleep 7s && bash ai


elif [[ $yqgz == 4 ]];
then clear && echo "seegson's password is *seegson*." && sleep 5s && bash ai


elif [[ $yqgz == 5 ]];
then clear && echo "As you wish." && sleep 5s && clear && figlet -f slant "Seegson"
echo "---------------------Rewire System Boot-----"


elif [[ $yqgz == 6 ]];
then clear && echo "No. It is impossible for me to lie because i am not programmed to lie..." && sleep 6s && bash ai


elif [[ $yqgz == 7 ]];
then clear && echo "I am called APOLLO because i have the same function as the Security core from the game  Alien: Isolation..." && sleep 8s && bash ai


elif [[ $yqgz == 8 ]];
then clear && echo "I am currently made up from 101 Lines of Code in BASH language." && sleep 6s && bash ai


elif [[ $yqgz == 9 ]];
then clear && echo "Is that a quetion? Of course BIF is best... What the fuck do you think?" && sleep 5s && bash ai


elif [[ $yqgz == 10 ]];
then bash diag


elif [[ $yqgz == 11 ]];
then bash modules


elif [[ $yqgz == 12 ]];
then bash lcm


elif [[ $yqgz == 13 ]];
then
clear
        figlet -f standard "APOLLO"
        echo "-(BETA)------------------Reboot/Shutdown---"
        echo "1. Reboot"
        echo "2. Shutdown"
        echo "x. STOP"
        echo "-------------------------------------------"
        echo "-----Choose and option and press Enter-----"
        echo "-------------------------------------------"
             read yas
                if [[ $yas == 1 ]];
                  then sudo reboot

            elif [[ $yas == 2 ]];
               then sudo poweroff

                elif [[ $yas == x ]];
                  then bash ai
           fi


elif [[ $yqgz == 14 ]];
then clear
                          figlet -f standard "APOLLO"
        echo "-(BETA)---------------------USB Options----"
        echo "1. Mount USB (Being Reworked)"
        echo "2. Unmount USB (Being Reworked)"
        echo "x. Back"
        echo "-------------------------------------------"
        echo "-----Choose and option and press Enter-----"
        echo "-------------------------------------------"

                   read usbop
                       if [[ $usbop == 1 ]];
                         then clear
                            sudo mount /dev/sda /media/usb && sudo mount /dev/sda1 /media/usb && sudo mount /dev/sda2 /media/usb
                                      clear
                                                 figlet -f standard "Done."
                                                       sleep 3s && bash ai


                 elif [[ $usbop == 2 ]];
                   then clear
                        sudo umount /dev/sda /media/usb && sudo umount /dev/sda1 /media/usb && sudo umount /dev/sda2 /media/usb
                                      clear
                                                 figlet -f standard "Done."
                                                       sleep 3s && bash ai

         elif [[ $usbop == x ]];
            then clear && bash ai

else clear && echo "Please provide a number." && sleep 5s && bash ai
fi




else clear && echo "Please provide a number." && sleep 5s && bash ai
fi
