#!/usr/bin/bash
clear

figlet -f standard "APOLLO"
echo "-(BETA)----------------------Core-------"


#greeting section
echo "1. Who are you? "
 echo "2. can you tell me the date today?"
  echo "3. I want to quit the small talk."
   echo "4. Can you lie?"
    echo "5. Why are you called APOLLO?"
     echo "6. How many lines of code are you?"
      echo "7. Switch to Advanced AI CORE"
       echo "8.-Modules-"
        echo "9. Locate File"
         echo "10. Reboot/Shutdown"
          echo "11. USB Options"
           echo "12. Future updates"
            echo "13. License of use"

echo "-------------------------------------------"
echo "-------Type a Number and press Enter-------"
echo "-------------------------------------------"


read yqgz

if [[ $yqgz == 1 ]];
then clear && echo "I am the Head AI CORE computer APOLLO." && sleep 5s && bash ai


elif [[ $yqgz == 2 ]];
then clear && echo "Yes of course." && date && sleep 5s && bash ai


elif [[ $yqgz == 3 ]];
then clear && echo "As you wish." && sleep 5s && clear


elif [[ $yqgz == 4 ]];
then clear && echo "No. It is impossible for me to lie because i am not programmed to lie..." && sleep 6s && bash ai


elif [[ $yqgz == 5 ]];
then clear && echo "I am called APOLLO because the owner of the project isn't good at giving names..." && sleep 8s && bash ai


elif [[ $yqgz == 6 ]];
then clear && echo "I am currently made up from 125 Lines of Code in BASH language." && sleep 6s && bash ai


elif [[ $yqgz == 7 ]];
then bash diag


elif [[ $yqgz == 8 ]];
then bash modules


elif [[ $yqgz == 9 ]];
then bash lcm


elif [[ $yqgz == 10 ]];
then
clear
        figlet -f standard "APOLLO"
        echo "-(BETA)------------------Reboot/Shutdown---"
        echo "1. Reboot"
        echo "2. Shutdown"
        echo "x. STOP"
        echo "-------------------------------------------"
        echo "-----Choose and option and press Enter-----"
        echo "-------------------------------------------"
             read yas
                if [[ $yas == 1 ]];
                  then sudo reboot

            elif [[ $yas == 2 ]];
               then sudo poweroff

                elif [[ $yas == x ]];
                  then bash ai
           fi


elif [[ $yqgz == 11 ]];
then clear
                          figlet -f standard "APOLLO"
        echo "-(BETA)---------------------USB Options----"
        echo "1. Mount USB (Being Reworked)"
        echo "2. Unmount USB (Being Reworked)"
        echo "x. Back"
        echo "-------------------------------------------"
        echo "-----Choose and option and press Enter-----"
        echo "-------------------------------------------"

                   read usbop
                       if [[ $usbop == 1 ]];
                         then clear
                            sudo mount /dev/sda /media/usb && sleep 3s && sudo mount /dev/sda1 /media/usb && sleep 3s && sudo mount /dev/sda2 /media/usb
                                      sleep 3s && clear
                                                 figlet -f standard "Done."
                                                       sleep 3s && bash ai


                 elif [[ $usbop == 2 ]];
                   then clear
                        sudo umount /dev/sda /media/usb && sleep 3s && sudo umount /dev/sda1 /media/usb && sleep 3s && sudo umount /dev/sda2 /media/usb
                                      sleep 3s clear
                                                 figlet -f standard "Done."
                                                       sleep 3s && bash ai

         elif [[ $usbop == x ]];
            then clear && bash ai

          else clear && echo "Please provide a number." && sleep 5s && bash ai
                                                       fi




elif [[ $yqgz == 12 ]];
then clear
                    figlet -f standard "APOLLO"
        echo "-(BETA)------------------Future updates----"
        echo "- New modules for Wifi Config"
        echo "- New storage viewer"
        echo "- New Ai terminal shortcut"
        echo "x. Back"
        echo "-------------------------------------------"
        echo "-------Type x and press Enter to exit------"
        echo "-------------------------------------------"


                      read gobackfromupdates
                           if [[ $gobackfromupdates == x ]];
                        then
                              bash ai
                          else clear && echo "Please provide a number." && sleep 5s && bash ai
                                                         fi







elif [[ $yqgz == 13 ]];
then
clear
              figlet -f standard "APOLLO"
        echo "-(BETA)------------------License----"
        echo "- DO NOT COPY OR COPY TO SELL!"
        echo "- You can make modules for the Ai menu if you want just ask me first..."
        echo "- If you have a problem just submit to the issues tab in the github page."
        echo "x. Back"
        echo "-------------------------------------------"
        echo "-------Type x and press Enter to exit------"
        echo "-------------------------------------------"
                             read exitfromlicense
                               if [[ $exitfromlicense == x ]];
                                     then bash ai
                      else
                                clear && echo "Please provide a number." && sleep 5s && bash ai
                                                         fi
























else clear && echo "Please provide a number." && sleep 5s && bash ai
fi
