#!/usr/bin/bash
clear


echo "What file do you want to locate? (If you want to quit then hold CTRL and press C)"

read name

clear

echo "Locating '$name'..." && sleep 3s && locate $name && echo "Closing in 7 seconds..." && sleep 7s && bash ai
fi




